//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

CustomerService_getCustomer_args = function(args) {
  this.customerId = null;
  if (args) {
    if (args.customerId !== undefined) {
      this.customerId = args.customerId;
    }
  }
};
CustomerService_getCustomer_args.prototype = {};
CustomerService_getCustomer_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.customerId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomerService_getCustomer_args.prototype.write = function(output) {
  output.writeStructBegin('CustomerService_getCustomer_args');
  if (this.customerId !== null && this.customerId !== undefined) {
    output.writeFieldBegin('customerId', Thrift.Type.I32, 1);
    output.writeI32(this.customerId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomerService_getCustomer_result = function(args) {
  this.success = null;
  this.unavailable = null;
  if (args instanceof CustomerUnavailable) {
    this.unavailable = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.unavailable !== undefined) {
      this.unavailable = args.unavailable;
    }
  }
};
CustomerService_getCustomer_result.prototype = {};
CustomerService_getCustomer_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Customer();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.unavailable = new CustomerUnavailable();
        this.unavailable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomerService_getCustomer_result.prototype.write = function(output) {
  output.writeStructBegin('CustomerService_getCustomer_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.unavailable !== null && this.unavailable !== undefined) {
    output.writeFieldBegin('unavailable', Thrift.Type.STRUCT, 1);
    this.unavailable.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomerServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
CustomerServiceClient.prototype = {};
CustomerServiceClient.prototype.getCustomer = function(customerId, callback) {
  this.send_getCustomer(customerId, callback); 
  if (!callback) {
    return this.recv_getCustomer();
  }
};

CustomerServiceClient.prototype.send_getCustomer = function(customerId, callback) {
  this.output.writeMessageBegin('getCustomer', Thrift.MessageType.CALL, this.seqid);
  var args = new CustomerService_getCustomer_args();
  args.customerId = customerId;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getCustomer();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

CustomerServiceClient.prototype.recv_getCustomer = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new CustomerService_getCustomer_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.unavailable) {
    throw result.unavailable;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'getCustomer failed: unknown result';
};
